CREATE TABLE public."AspNetUsers"
(
    "Id" text COLLATE pg_catalog."default" NOT NULL,
    "Discriminator" text COLLATE pg_catalog."default" NOT NULL,
    "FullName" text COLLATE pg_catalog."default",
    "Pays" text COLLATE pg_catalog."default",
    "Ville" text COLLATE pg_catalog."default",
    "Diplome" text COLLATE pg_catalog."default",
    "Specialite" text COLLATE pg_catalog."default",
    "Nb_annees_experience" integer,
    "Date_naissance" text COLLATE pg_catalog."default",
    "UserName" character varying(256) COLLATE pg_catalog."default",
    "NormalizedUserName" character varying(256) COLLATE pg_catalog."default",
    "Email" character varying(256) COLLATE pg_catalog."default",
    "NormalizedEmail" character varying(256) COLLATE pg_catalog."default",
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text COLLATE pg_catalog."default",
    "SecurityStamp" text COLLATE pg_catalog."default",
    "ConcurrencyStamp" text COLLATE pg_catalog."default",
    "PhoneNumber" text COLLATE pg_catalog."default",
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE public."AspNetUserTokens"
(
    "UserId" text COLLATE pg_catalog."default" NOT NULL,
    "LoginProvider" character varying(128) COLLATE pg_catalog."default" NOT NULL,
    "Name" character varying(128) COLLATE pg_catalog."default" NOT NULL,
    "Value" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId")
        REFERENCES public."AspNetUsers" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);

CREATE TABLE public."AspNetRoles"
(
    "Id" text COLLATE pg_catalog."default" NOT NULL,
    "Name" character varying(256) COLLATE pg_catalog."default",
    "NormalizedName" character varying(256) COLLATE pg_catalog."default",
    "ConcurrencyStamp" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE public."AspNetRoleClaims"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "RoleId" text COLLATE pg_catalog."default" NOT NULL,
    "ClaimType" text COLLATE pg_catalog."default",
    "ClaimValue" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId")
        REFERENCES public."AspNetRoles" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);


CREATE TABLE public."AspNetUserClaims"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "UserId" text COLLATE pg_catalog."default" NOT NULL,
    "ClaimType" text COLLATE pg_catalog."default",
    "ClaimValue" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId")
        REFERENCES public."AspNetUsers" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);


CREATE TABLE public."AspNetUserLogins"
(
    "LoginProvider" character varying(128) COLLATE pg_catalog."default" NOT NULL,
    "ProviderKey" character varying(128) COLLATE pg_catalog."default" NOT NULL,
    "ProviderDisplayName" text COLLATE pg_catalog."default",
    "UserId" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId")
        REFERENCES public."AspNetUsers" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);

CREATE TABLE public."AspNetUserRoles"
(
    "UserId" text COLLATE pg_catalog."default" NOT NULL,
    "RoleId" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId")
        REFERENCES public."AspNetRoles" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId")
        REFERENCES public."AspNetUsers" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);

CREATE TABLE public."Departements"
(
    "DepartementID" uuid NOT NULL,
    "Code" text COLLATE pg_catalog."default",
    "Libelle" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_Departements" PRIMARY KEY ("DepartementID")
);


CREATE TABLE public."Offres"
(
    "OffreID" uuid NOT NULL,
    "NomOffre" text COLLATE pg_catalog."default" NOT NULL,
    "Pays" text COLLATE pg_catalog."default" NOT NULL,
    "Region" text COLLATE pg_catalog."default" NOT NULL,
    "Date_debut" text COLLATE pg_catalog."default",
    "Qualites_interpersonnelles" text COLLATE pg_catalog."default",
    "Competences_techniques" text COLLATE pg_catalog."default",
    "Diplome_demande" text COLLATE pg_catalog."default" NOT NULL,
    "Experience_demandee" integer NOT NULL,
    salaire bigint NOT NULL,
    "Type_contrat" text COLLATE pg_catalog."default",
    departement text COLLATE pg_catalog."default",
    "DepartementsDepartementID" uuid,
    CONSTRAINT "PK_Offres" PRIMARY KEY ("OffreID"),
    CONSTRAINT "FK_Offres_Departements_DepartementsDepartementID" FOREIGN KEY ("DepartementsDepartementID")
        REFERENCES public."Departements" ("DepartementID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE RESTRICT
);

CREATE TABLE public."Candidatures"
(
    "CandidatureID" uuid NOT NULL,
    "Date_postulation" text COLLATE pg_catalog."default",
    "Etat" text COLLATE pg_catalog."default",
    "Curriculum_Vitae" text COLLATE pg_catalog."default" NOT NULL,
    "Score" real NOT NULL,
    "OffreFK" uuid NOT NULL,
    "CandidatFK" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_Candidatures" PRIMARY KEY ("CandidatureID"),
    CONSTRAINT "FK_Candidatures_AspNetUsers_CandidatFK" FOREIGN KEY ("CandidatFK")
        REFERENCES public."AspNetUsers" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE RESTRICT,
    CONSTRAINT "FK_Candidatures_Offres_OffreFK" FOREIGN KEY ("OffreFK")
        REFERENCES public."Offres" ("OffreID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);
CREATE TABLE public."EntretienRHs"
(
    "EntretienID" uuid NOT NULL,
    "Destination" text COLLATE pg_catalog."default",
    "Equipe_recrutement" text COLLATE pg_catalog."default",
    "Type_entretien" text COLLATE pg_catalog."default",
    "Localisation" text COLLATE pg_catalog."default" NOT NULL,
    "Duree" text COLLATE pg_catalog."default" NOT NULL,
    "Date" text COLLATE pg_catalog."default" NOT NULL,
    "Heure" integer NOT NULL,
    "RendezVousCandidatureID" uuid,
    CONSTRAINT "PK_EntretienRHs" PRIMARY KEY ("EntretienID"),
    CONSTRAINT "FK_EntretienRHs_Candidatures_RendezVousCandidatureID" FOREIGN KEY ("RendezVousCandidatureID")
        REFERENCES public."Candidatures" ("CandidatureID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE RESTRICT
);

CREATE TABLE public."TestTechniques"
(
    "TestID" uuid NOT NULL,
    "Destination" text COLLATE pg_catalog."default",
    "Date_depot" text COLLATE pg_catalog."default",
    "Duree" text COLLATE pg_catalog."default" NOT NULL,
    lien_test text COLLATE pg_catalog."default" NOT NULL,
    "TestCandidatureID" uuid NOT NULL,
    CONSTRAINT "PK_TestTechniques" PRIMARY KEY ("TestID"),
    CONSTRAINT "FK_TestTechniques_Candidatures_TestCandidatureID" FOREIGN KEY ("TestCandidatureID")
        REFERENCES public."Candidatures" ("CandidatureID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);

 
ALTER TABLE public."Offres"
Add COLUMN "diplome" text COLLATE pg_catalog."default"

